linux_display_server wayland
# font_family Lilex
font_family FiraCode Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0
disable_ligatures never
cursor_shape beam
scrollback_lines 10000
repaint_delay 6
sync_to_monitor yes
confirm_os_window_close 0

shell_integration no-title no-cwd

# window
window_padding_width 6
background_opacity  0.85

# tab bar
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style angled
tab_fade 1
active_tab_font_style   bold
inactive_tab_font_style bold

# keybinds
map ctrl+t new_tab_with_cwd
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
# NOTE: ctrl+w is needed for nvim
map ctrl+equal change_font_size current +1.0
map ctrl+minus change_font_size current -1.0
map ctrl+0 change_font_size current 0


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
